spring:
  application:
    name: cinepass-api
  jpa:
    hibernate:
      ddl-auto: update
    defer-datasource-initialization: true
  sql:
    init:
      mode: always
  datasource:
    url: jdbc:mysql://localhost:3306/moviedb?createDatabaseIfNotExist=true
    username: root
    password: tiger
  jackson:
    serialization:
      write-dates-as-timestamps: false
    deserialization:
      fail-on-unknown-properties: false
  security:
    oauth2:
      client:
        registration:
          github:
            clientId: ${GITHUB_CLIENT_ID}
            clientSecret: ${GITHUB_CLIENT_SECRET}
            scope: read:user, user:email
          google:
            clientId: ${GOOGLE_CLIENT_ID}
            clientSecret: ${GOOGLE_CLIENT_SECRET}
            scope: profile, email

  mail:
    host: sandbox.smtp.mailtrap.io
    port: 2525
    username: c51559ecb9273a
    password: e5f1c77f337742
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          connectiontimeout: 5000
          timeout: 3000
          writetimeout: 5000

app:
  name: CinePass
  jwt:
    # Signing key for HS512 algorithm
    # In http://www.allkeysgenerator.com/ you can generate all kinds of keys
    secret: v9y$B&E)H@MbQeThWmZq4t7w!z%C*F-JaNdRfUjXn2r5u8x/A?D(G+KbPeShVkYp
    expiration:
      minutes: 10080
  oauth2:
    redirectUri: http://localhost:3000/oauth2/redirect
  cors:
    allowed-origins: http://localhost:3000

logging:
  level:
    org.springframework.security: DEBUG
    org.springframework.mail: DEBUG
    javax.mail: DEBUG
    com.moviebooking.service.EmailService: DEBUG
    # org.hibernate.SQL: DEBUG